[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/huggingface/candle"]
git = "https://github.com/huggingface/candle"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
