# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  # Review settings
  review_status: true
  high_level_summary: true
  poem: false
  request_changes_workflow: true

  # Path filters (review everything)
  path_filters:
    - "**/*.rs"
    - "**/*.toml"
    - "**/*.md"

  # Auto reviews on all PRs (fixed regex)
  auto_review:
    enabled: true
    base_branches:
      - ".*"
