version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: niodoo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./logs:/metrics:ro  # Mount logs directory where .prom files are stored
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - niodoo-monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: niodoo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=niodoo123  # Change this!
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - niodoo-monitoring

volumes:
  prometheus-data:
  grafana-data:

networks:
  niodoo-monitoring:
    driver: bridge
