pub mod api_clients;
pub mod benchmark;
pub mod circuit_breaker;
pub mod compass;
pub mod config;
pub mod consonance;
pub mod curator;
pub mod curator_parser;
pub mod data;
pub mod embedded_qdrant;
pub mod embedding;
pub mod erag;
pub mod eval;
pub mod generation;
#[cfg(feature = "svc")]
pub mod grpc_inference;
pub mod health;
pub mod hyperfocus;
pub mod learning;
pub mod lora_trainer;
pub mod mcts;
pub mod mcts_config;
pub mod metrics;
pub mod rce;
pub mod mock_qdrant;
pub mod mock_vllm;
// Legacy pipeline module - commented out as we're using the new pipeline/ structure
// #[path = "pipeline_legacy.rs"]
// pub mod pipeline;
pub mod conversation_log;
pub mod degradation_tiers;
pub mod emotional_graph;
pub mod gpu_fitness;
#[cfg(feature = "gpu")]
pub mod gpu_fusion;
#[cfg(feature = "gpu")]
pub mod gpu_memory_pool;
#[cfg(feature = "gpu")]
pub mod gpu_async;
#[cfg(feature = "gpu")]
pub mod gpu_batch;
#[cfg(feature = "gpu")]
pub mod gpu_prefetch;
#[cfg(feature = "gpu")]
pub mod gpu_consonance;
pub mod graph_exporter;
pub mod memory_architect;
pub mod memory_consolidation;
pub mod pipeline;
pub mod resource_budget;
pub mod security;
pub mod signals;
pub mod tcs_analysis;
pub mod tcs_lora;
pub mod tcs_predictor;
pub mod temporal_tda;
pub mod token_manager;
pub mod tokenizer;
pub mod topology_crawler;
pub mod topology_memory;
pub mod torus;
pub mod tracing_integration;
pub mod util;
pub mod validation;
pub mod vector_store;
pub mod weight_evolution;
pub mod weighted_episodic_mem;
pub mod ntoken_client;
#[cfg(feature = "svc")]
pub mod training_service;
