[package]
name = "niodoo_real_integrated"
version = "0.1.0"
edition = "2021"
authors = ["Niodoo Torque Team <torque@niodoo.ai>"]
description = "Full NIODOO pipeline integration with real Qwen embeddings, ERAG memory, tokenizer promotion, vLLM hybrid generation, and learning loop."
license = "MIT"

[features]
default = ["beelink"]
beelink = []
5080-q = []
pyo3 = []

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
prometheus = { version = "0.13", features = ["nightly"] }
rand = { version = "0.8", features = ["std", "serde"] }
rand_distr = "0.4"
regex = "1.10"
tokio = { version = "1", features = ["full"] }
nalgebra = { version = "0.33", features = ["serde-serialize"] }
csv = "1.3"
thiserror = "1.0"
tcs-ml = { path = "../tcs-ml", features = ["onnx"] }
# Removed non-existent "candle" feature
tcs-tda = { path = "../tcs-tda" }
tcs-knot = { path = "../tcs-knot" }
tcs-tqft = { path = "../tcs-tqft" }
tcs-core = { path = "../tcs-core" }
axum = "0.7"
once_cell = "1.19"
futures = "0.3"
uuid = { workspace = true }
plotters = "0.3"
blake3 = { workspace = true }
lru = { workspace = true }
redis = { version = "0.24", default-features = false, features = ["tokio-comp", "connection-manager"] }
bincode = "1"
candle-core = "0.8"
candle-nn = "0.8"
safetensors = "0.4"
num-complex = "0.4"
rayon = "1.10"

qdrant-client = "1.9"
urlencoding = "2.1"
pyo3 = { version = "0.22", features = ["auto-initialize"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
[dev-dependencies]
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
criterion = "0.5"

[[bench]]
name = "niodoo_real_bench"
harness = false

[[bin]]
name = "niodoo_real_integrated"
path = "src/main.rs"

[[bin]]
name = "rut_gauntlet"
path = "src/bin/rut_gauntlet.rs"

[[bin]]
name = "topology_spider"
path = "src/bin/topology_spider.rs"

[[bin]]
name = "test_healing_integration"
path = "src/bin/test_healing_integration.rs"

[[bin]]
name = "million_cycle_test"
path = "src/bin/million_cycle_test.rs"
