[package]
name = "niodoo_real_integrated"
version = "0.1.0"
edition = "2021"
authors = ["Niodoo Torque Team <torque@niodoo.ai>"]
description = "Full NIODOO pipeline integration with real Qwen embeddings, ERAG memory, tokenizer promotion, vLLM hybrid generation, and learning loop."
license = "MIT"

[features]
default = ["beelink"]
beelink = []
5080-q = []

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
prometheus = "0.13"
rand = { version = "0.8", features = ["std", "serde"] }
rand_distr = "0.4"
tokio = { version = "1", features = ["full"] }
nalgebra = { version = "0.33", features = ["serde-serialize"] }
csv = "1.3"
thiserror = "1.0"
tcs-ml = { path = "../tcs-ml", features = ["onnx"] }
once_cell = "1.19"
futures = "0.3"
uuid = { workspace = true }
plotters = "0.3"
axum = { workspace = true }

qdrant-client = { version = "1.7", features = ["grpc"] }
urlencoding = "2.1"
[dev-dependencies]
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
criterion = "0.5"

[[bench]]
name = "niodoo_real_bench"
harness = false

[[bin]]
name = "niodoo_real_integrated"
path = "src/main.rs"

[[bin]]
name = "rut_gauntlet"
path = "src/bin/rut_gauntlet.rs"