"""Curator service for System 2 (quality scoring + feedback).

This module evaluates Granite responses by combining ROUGE-L signal with
LLM-based qualitative feedback. Usage:

    from curator import Curator
    curator = Curator()
    result = curator.score_response(prompt, response)

The result dictionary contains:
    - rouge_l: float (F-measure)
    - quality_score: int | None (0-10 rating parsed from Granite)
    - feedback: str (free-form justification)
    - raw_completion: str (exact Granite output for traceability)
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from typing import Any, Dict, List

import torch
from rouge_score import rouge_scorer
from transformers import AutoModelForCausalLM, AutoTokenizer


DEFAULT_MODEL_PATH = "/workspace/Niodoo-AI/outputs/qwen25-small-topology-20251105/merged"


@dataclass
class CuratorConfig:
    model_path: str = DEFAULT_MODEL_PATH
    device_map: str = "auto"
    max_new_tokens: int = 128
    repetition_penalty: float = 1.05

    @classmethod
    def from_env(cls) -> "CuratorConfig":
        max_tokens_env = os.getenv("NIODOO_CURATOR_MAX_NEW_TOKENS")
        if max_tokens_env is None:
            max_tokens_env = os.getenv("NIODOO_CURATOR_MAX_TOKENS", "128")

        return cls(
            model_path=os.getenv("NIODOO_CURATOR_MODEL_PATH", DEFAULT_MODEL_PATH),
            device_map=os.getenv("NIODOO_CURATOR_DEVICE_MAP", "auto"),
            max_new_tokens=int(max_tokens_env),
            repetition_penalty=float(
                os.getenv("NIODOO_CURATOR_REPETITION_PENALTY", "1.05")
            ),
        )


class Curator:
    def __init__(self, config: CuratorConfig | None = None) -> None:
        self.config = config or CuratorConfig.from_env()
        self._scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)

        self._tokenizer = AutoTokenizer.from_pretrained(
            self.config.model_path,
            trust_remote_code=True,
        )
        if self._tokenizer.pad_token is None:
            self._tokenizer.pad_token = self._tokenizer.eos_token

        torch_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32
        self._model = AutoModelForCausalLM.from_pretrained(
            self.config.model_path,
            device_map=self.config.device_map,
            dtype=torch_dtype,
            trust_remote_code=True,
        )
        self._model.eval()

        self._device = next(self._model.parameters()).device

    def score_response(self, prompt: str, response: str) -> Dict[str, Any]:
        """Return quality metadata for the given model response."""
        rouge = self._scorer.score(prompt, response)["rougeL"].fmeasure
        completion_payload = self._build_quality_prompt(prompt, response)
        raw_completion = self._generate_local_completion(completion_payload["messages"])
        score, feedback = self._parse_quality_response(raw_completion)

        return {
            "rouge_l": rouge,
            "quality_score": score,
            "feedback": feedback,
            "raw_completion": raw_completion,
        }

    def _build_quality_prompt(self, prompt: str, response: str) -> Dict[str, Any]:
        system_msg = (
            "You are the NIODOO Memory Curator. Your job is to evaluate candidate "
            "memories generated by the main Granite model. Score from 0 (reject) "
            "to 10 (store immediately) based on factual accuracy, topological "
            "alignment, novelty, and actionability. Be strict—only high-quality "
            "insights should pass into the learning buffer. Always respond with "
            'strict JSON exactly {"score": <int>, "feedback": <string>} and no '
            "additional prose."
        )
        user_msg = (
            "Evaluate the following exchange and return JSON only.\n\n"
            "If the response is hallucinated, redundant, or not grounded in topological "
            "memory cues, assign a low score and explain why in feedback.\n\n"
            f"Prompt:\n{prompt.strip()}\n\n"
            f"Response:\n{response.strip()}\n\n"
            'Return JSON in the shape {"score": int, "feedback": str}.'
        )

        return {
            "messages": [
                {"role": "system", "content": system_msg},
                {"role": "user", "content": user_msg},
            ],
        }

    def _generate_local_completion(self, messages: List[Dict[str, str]]) -> str:
        chat_prompt = self._tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = self._tokenizer(
            chat_prompt,
            return_tensors="pt",
        )
        inputs = {k: v.to(self._device) for k, v in inputs.items()}

        generation_kwargs: Dict[str, Any] = {
            "max_new_tokens": self.config.max_new_tokens,
            "repetition_penalty": self.config.repetition_penalty,
            "pad_token_id": self._tokenizer.pad_token_id,
            "eos_token_id": self._tokenizer.eos_token_id,
            "do_sample": False,
        }

        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                **generation_kwargs,
            )

        generated = output_ids[0, inputs["input_ids"].shape[-1] :]
        text = self._tokenizer.decode(generated, skip_special_tokens=True)
        return text.strip()

    @staticmethod
    def _parse_quality_response(raw: str) -> tuple[int | None, str]:
        raw = raw.strip()

        payload: Dict[str, Any] | None = None
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            json_match = re.search(r"\{.*\}", raw, flags=re.DOTALL)
            if json_match:
                try:
                    payload = json.loads(json_match.group(0))
                except json.JSONDecodeError:
                    payload = None

        if isinstance(payload, dict):
            score = payload.get("score")
            feedback = payload.get("feedback", "")

            if isinstance(score, (int, float)):
                score_int = int(round(float(score)))
                return max(0, min(score_int, 10)), str(feedback)

            if isinstance(score, str):
                score_clean = score.strip()
                if score_clean.isdigit():
                    return max(0, min(int(score_clean), 10)), str(feedback)
                try:
                    score_float = float(score_clean)
                except ValueError:
                    pass
                else:
                    score_int = int(round(score_float))
                    return max(0, min(score_int, 10)), str(feedback)

        score_val: int | None = None
        match = re.search(r"score\s*[:=]\s*(\d{1,2})", raw, flags=re.IGNORECASE)
        if match:
            try:
                score_val = int(match.group(1))
            except ValueError:
                score_val = None
        else:
            fraction_match = re.search(
                r"(\d{1,2})\s*(?:/10|out of\s*10)",
                raw,
                flags=re.IGNORECASE,
            )
            if fraction_match:
                try:
                    score_val = int(fraction_match.group(1))
                except ValueError:
                    score_val = None

        if score_val is None:
            word_map = {
                "zero": 0,
                "one": 1,
                "two": 2,
                "three": 3,
                "four": 4,
                "five": 5,
                "six": 6,
                "seven": 7,
                "eight": 8,
                "nine": 9,
                "ten": 10,
            }
            for word, value in word_map.items():
                pattern = rf"\b{word}\b\s*(?:/10|out of\s*(?:ten|10))?"
                if re.search(pattern, raw, flags=re.IGNORECASE):
                    score_val = value
                    break

        if score_val is not None:
            score_val = max(0, min(score_val, 10))

        return score_val, raw


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Curator quality scoring tool")
    parser.add_argument("prompt", help="Original user prompt")
    parser.add_argument("response", help="Granite response text")
    args = parser.parse_args()

    curator = Curator()
    result = curator.score_response(args.prompt, args.response)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
