// This file is @generated by prost-build.
/// Tensor shape information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TensorShape {
    /// Dimensions: \[batch, seq_len, ...\]
    #[prost(int64, repeated, tag = "1")]
    pub dims: ::prost::alloc::vec::Vec<i64>,
}
/// Tensor data for ONNX inference
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tensor {
    #[prost(enumeration = "TensorDataType", tag = "1")]
    pub dtype: i32,
    #[prost(message, optional, tag = "2")]
    pub shape: ::core::option::Option<TensorShape>,
    /// Raw bytes of tensor data
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// For FP32/F16 data
    #[prost(float, repeated, tag = "4")]
    pub float_data: ::prost::alloc::vec::Vec<f32>,
    /// For INT64 data
    #[prost(int64, repeated, tag = "5")]
    pub int64_data: ::prost::alloc::vec::Vec<i64>,
    /// For INT32 data
    #[prost(int32, repeated, tag = "6")]
    pub int32_data: ::prost::alloc::vec::Vec<i32>,
}
/// Model inference request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceRequest {
    /// ONNX model identifier
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    /// Input tensors by name
    #[prost(map = "string, message", tag = "2")]
    pub inputs: ::std::collections::HashMap<::prost::alloc::string::String, Tensor>,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<InferenceOptions>,
}
/// Inference options for H200 optimization
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceOptions {
    /// Use FP8 quantization (H200)
    #[prost(bool, tag = "1")]
    pub use_fp8: bool,
    /// Batch size (up to 1024 for H200)
    #[prost(int32, tag = "2")]
    pub batch_size: i32,
    /// HTTP/2 multiplexing (default: 128)
    #[prost(int32, tag = "3")]
    pub max_concurrent_streams: i32,
    /// CUDA Graphs for signal-slot cycles
    #[prost(bool, tag = "4")]
    pub enable_cuda_graph: bool,
    /// "CUDA" or "CUDAExecutionProvider"
    #[prost(string, tag = "5")]
    pub execution_provider: ::prost::alloc::string::String,
    /// GPU device ID (default: 0)
    #[prost(int32, tag = "6")]
    pub gpu_device_id: i32,
}
/// Inference response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceResponse {
    /// Output tensors by name
    #[prost(map = "string, message", tag = "1")]
    pub outputs: ::std::collections::HashMap<::prost::alloc::string::String, Tensor>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<InferenceMetadata>,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// Inference metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceMetadata {
    /// Inference latency in milliseconds
    #[prost(double, tag = "1")]
    pub inference_time_ms: f64,
    /// GPU memory usage
    #[prost(int64, tag = "2")]
    pub gpu_memory_used_bytes: i64,
    #[prost(int32, tag = "3")]
    pub batch_size: i32,
    #[prost(bool, tag = "4")]
    pub used_fp8: bool,
    #[prost(string, tag = "5")]
    pub execution_provider: ::prost::alloc::string::String,
}
/// Model loading request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadModelRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    /// Path to ONNX model file
    #[prost(string, tag = "2")]
    pub model_path: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub default_options: ::core::option::Option<InferenceOptions>,
}
/// Model loading response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadModelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub model_info: ::core::option::Option<ModelInfo>,
}
/// Model information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelInfo {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub input_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub output_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, message", tag = "4")]
    pub input_shapes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        TensorShape,
    >,
    #[prost(map = "string, message", tag = "5")]
    pub output_shapes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        TensorShape,
    >,
    #[prost(int64, tag = "6")]
    pub model_size_bytes: i64,
    #[prost(bool, tag = "7")]
    pub supports_fp8: bool,
}
/// Batch inference request (for multiple prompts)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchInferenceRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    /// Batch of requests
    #[prost(message, repeated, tag = "2")]
    pub requests: ::prost::alloc::vec::Vec<InferenceRequest>,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<InferenceOptions>,
}
/// Batch inference response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchInferenceResponse {
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<InferenceResponse>,
    #[prost(message, optional, tag = "2")]
    pub batch_metadata: ::core::option::Option<BatchMetadata>,
}
/// Batch metadata
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BatchMetadata {
    #[prost(int32, tag = "1")]
    pub batch_size: i32,
    #[prost(double, tag = "2")]
    pub total_time_ms: f64,
    #[prost(double, tag = "3")]
    pub avg_time_per_item_ms: f64,
    #[prost(int64, tag = "4")]
    pub peak_gpu_memory_bytes: i64,
}
/// Health check request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {
    #[prost(string, tag = "1")]
    pub service: ::prost::alloc::string::String,
}
/// Health check response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(enumeration = "health_check_response::ServingStatus", tag = "1")]
    pub status: i32,
    /// GPU device information
    #[prost(string, tag = "2")]
    pub gpu_info: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub loaded_models_count: i32,
}
/// Nested message and enum types in `HealthCheckResponse`.
pub mod health_check_response {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ServingStatus {
        Unknown = 0,
        Serving = 1,
        NotServing = 2,
    }
    impl ServingStatus {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Serving => "SERVING",
                Self::NotServing => "NOT_SERVING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "SERVING" => Some(Self::Serving),
                "NOT_SERVING" => Some(Self::NotServing),
                _ => None,
            }
        }
    }
}
/// Tensor data types supported by ONNX Runtime
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TensorDataType {
    Unspecified = 0,
    Float32 = 1,
    Float16 = 2,
    Int64 = 3,
    Int32 = 4,
    Uint8 = 5,
    /// H200 FP8 support
    Fp8E4m3fn = 6,
    /// H200 FP8 support
    Fp8E5m2 = 7,
}
impl TensorDataType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TENSOR_DATA_TYPE_UNSPECIFIED",
            Self::Float32 => "TENSOR_DATA_TYPE_FLOAT32",
            Self::Float16 => "TENSOR_DATA_TYPE_FLOAT16",
            Self::Int64 => "TENSOR_DATA_TYPE_INT64",
            Self::Int32 => "TENSOR_DATA_TYPE_INT32",
            Self::Uint8 => "TENSOR_DATA_TYPE_UINT8",
            Self::Fp8E4m3fn => "TENSOR_DATA_TYPE_FP8_E4M3FN",
            Self::Fp8E5m2 => "TENSOR_DATA_TYPE_FP8_E5M2",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TENSOR_DATA_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "TENSOR_DATA_TYPE_FLOAT32" => Some(Self::Float32),
            "TENSOR_DATA_TYPE_FLOAT16" => Some(Self::Float16),
            "TENSOR_DATA_TYPE_INT64" => Some(Self::Int64),
            "TENSOR_DATA_TYPE_INT32" => Some(Self::Int32),
            "TENSOR_DATA_TYPE_UINT8" => Some(Self::Uint8),
            "TENSOR_DATA_TYPE_FP8_E4M3FN" => Some(Self::Fp8E4m3fn),
            "TENSOR_DATA_TYPE_FP8_E5M2" => Some(Self::Fp8E5m2),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod onnx_inference_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ONNX Inference Service
    #[derive(Debug, Clone)]
    pub struct OnnxInferenceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OnnxInferenceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OnnxInferenceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OnnxInferenceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OnnxInferenceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Load an ONNX model
        pub async fn load_model(
            &mut self,
            request: impl tonic::IntoRequest<super::LoadModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoadModelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.OnnxInferenceService/LoadModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("niodoo.rce.OnnxInferenceService", "LoadModel"));
            self.inner.unary(req, path, codec).await
        }
        /// Single inference request
        pub async fn infer(
            &mut self,
            request: impl tonic::IntoRequest<super::InferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InferenceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.OnnxInferenceService/Infer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("niodoo.rce.OnnxInferenceService", "Infer"));
            self.inner.unary(req, path, codec).await
        }
        /// Batch inference (for H200 optimization)
        pub async fn batch_infer(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchInferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchInferenceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.OnnxInferenceService/BatchInfer",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("niodoo.rce.OnnxInferenceService", "BatchInfer"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Streaming inference (for recursive loops)
        pub async fn stream_infer(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::InferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::InferenceResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.OnnxInferenceService/StreamInfer",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("niodoo.rce.OnnxInferenceService", "StreamInfer"),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Health check
        pub async fn check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.OnnxInferenceService/Check",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("niodoo.rce.OnnxInferenceService", "Check"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod onnx_inference_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with OnnxInferenceServiceServer.
    #[async_trait]
    pub trait OnnxInferenceService: std::marker::Send + std::marker::Sync + 'static {
        /// Load an ONNX model
        async fn load_model(
            &self,
            request: tonic::Request<super::LoadModelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoadModelResponse>,
            tonic::Status,
        >;
        /// Single inference request
        async fn infer(
            &self,
            request: tonic::Request<super::InferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InferenceResponse>,
            tonic::Status,
        >;
        /// Batch inference (for H200 optimization)
        async fn batch_infer(
            &self,
            request: tonic::Request<super::BatchInferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchInferenceResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamInfer method.
        type StreamInferStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::InferenceResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Streaming inference (for recursive loops)
        async fn stream_infer(
            &self,
            request: tonic::Request<tonic::Streaming<super::InferenceRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamInferStream>,
            tonic::Status,
        >;
        /// Health check
        async fn check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
    }
    /// ONNX Inference Service
    #[derive(Debug)]
    pub struct OnnxInferenceServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> OnnxInferenceServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for OnnxInferenceServiceServer<T>
    where
        T: OnnxInferenceService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/niodoo.rce.OnnxInferenceService/LoadModel" => {
                    #[allow(non_camel_case_types)]
                    struct LoadModelSvc<T: OnnxInferenceService>(pub Arc<T>);
                    impl<
                        T: OnnxInferenceService,
                    > tonic::server::UnaryService<super::LoadModelRequest>
                    for LoadModelSvc<T> {
                        type Response = super::LoadModelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoadModelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OnnxInferenceService>::load_model(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoadModelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.OnnxInferenceService/Infer" => {
                    #[allow(non_camel_case_types)]
                    struct InferSvc<T: OnnxInferenceService>(pub Arc<T>);
                    impl<
                        T: OnnxInferenceService,
                    > tonic::server::UnaryService<super::InferenceRequest>
                    for InferSvc<T> {
                        type Response = super::InferenceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InferenceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OnnxInferenceService>::infer(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InferSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.OnnxInferenceService/BatchInfer" => {
                    #[allow(non_camel_case_types)]
                    struct BatchInferSvc<T: OnnxInferenceService>(pub Arc<T>);
                    impl<
                        T: OnnxInferenceService,
                    > tonic::server::UnaryService<super::BatchInferenceRequest>
                    for BatchInferSvc<T> {
                        type Response = super::BatchInferenceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchInferenceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OnnxInferenceService>::batch_infer(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchInferSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.OnnxInferenceService/StreamInfer" => {
                    #[allow(non_camel_case_types)]
                    struct StreamInferSvc<T: OnnxInferenceService>(pub Arc<T>);
                    impl<
                        T: OnnxInferenceService,
                    > tonic::server::StreamingService<super::InferenceRequest>
                    for StreamInferSvc<T> {
                        type Response = super::InferenceResponse;
                        type ResponseStream = T::StreamInferStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::InferenceRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OnnxInferenceService>::stream_infer(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamInferSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.OnnxInferenceService/Check" => {
                    #[allow(non_camel_case_types)]
                    struct CheckSvc<T: OnnxInferenceService>(pub Arc<T>);
                    impl<
                        T: OnnxInferenceService,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for CheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OnnxInferenceService>::check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for OnnxInferenceServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "niodoo.rce.OnnxInferenceService";
    impl<T> tonic::server::NamedService for OnnxInferenceServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Persistent homology barcode
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Barcode {
    /// Homology dimension (0, 1, 2, ...)
    #[prost(int32, tag = "1")]
    pub dimension: i32,
    /// Birth time
    #[prost(double, tag = "2")]
    pub birth: f64,
    /// Death time
    #[prost(double, tag = "3")]
    pub death: f64,
    /// death - birth
    #[prost(double, tag = "4")]
    pub persistence: f64,
}
/// Persistent homology diagram
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PersistenceDiagram {
    #[prost(message, repeated, tag = "1")]
    pub barcodes: ::prost::alloc::vec::Vec<Barcode>,
    #[prost(int32, tag = "2")]
    pub max_dimension: i32,
}
/// Betti numbers (rank of homology groups)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BettiNumbers {
    /// Connected components
    #[prost(int32, tag = "1")]
    pub beta_0: i32,
    /// Holes
    #[prost(int32, tag = "2")]
    pub beta_1: i32,
    /// Voids
    #[prost(int32, tag = "3")]
    pub beta_2: i32,
    /// Higher dimensions
    #[prost(int32, repeated, tag = "4")]
    pub higher_betti: ::prost::alloc::vec::Vec<i32>,
}
/// Persistent Laplacian spectrum
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LaplacianSpectrum {
    #[prost(double, repeated, tag = "1")]
    pub eigenvalues: ::prost::alloc::vec::Vec<f64>,
    /// Flattened eigenvectors
    #[prost(double, repeated, tag = "2")]
    pub eigenvectors: ::prost::alloc::vec::Vec<f64>,
    /// Shape for reshaping
    #[prost(int32, repeated, tag = "3")]
    pub eigenvector_shape: ::prost::alloc::vec::Vec<i32>,
}
/// Topological signature (for vector storage in Qdrant)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopologicalSignature {
    /// Flattened PH features
    #[prost(double, repeated, tag = "1")]
    pub persistent_homology_features: ::prost::alloc::vec::Vec<f64>,
    #[prost(message, optional, tag = "2")]
    pub betti_numbers: ::core::option::Option<BettiNumbers>,
    #[prost(double, tag = "3")]
    pub topological_entropy: f64,
    /// Top eigenvectors
    #[prost(double, repeated, tag = "4")]
    pub laplacian_features: ::prost::alloc::vec::Vec<f64>,
    /// Dimension for Qdrant storage
    #[prost(int32, tag = "5")]
    pub embedding_dimension: i32,
}
/// Topological data request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopologicalDataRequest {
    /// Identifier for the data
    #[prost(string, tag = "1")]
    pub data_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<TopologicalData>,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<TopologyOptions>,
}
/// Topological data
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopologicalData {
    /// Flattened point cloud \[n_points, dim\]
    #[prost(float, repeated, tag = "1")]
    pub point_cloud: ::prost::alloc::vec::Vec<f32>,
    /// \[n_points, dim\]
    #[prost(int32, repeated, tag = "2")]
    pub point_cloud_shape: ::prost::alloc::vec::Vec<i32>,
    /// Distance matrix (if precomputed)
    #[prost(float, repeated, tag = "3")]
    pub distance_matrix: ::prost::alloc::vec::Vec<f32>,
    #[prost(int32, repeated, tag = "4")]
    pub distance_matrix_shape: ::prost::alloc::vec::Vec<i32>,
    /// Threshold for persistent homology
    #[prost(double, tag = "5")]
    pub epsilon: f64,
    /// Maximum homology dimension
    #[prost(int32, tag = "6")]
    pub max_dimension: i32,
}
/// Topology computation options
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TopologyOptions {
    /// Compute persistent homology
    #[prost(bool, tag = "1")]
    pub compute_persistence: bool,
    /// Compute Betti numbers
    #[prost(bool, tag = "2")]
    pub compute_betti: bool,
    /// Compute Laplacian spectrum
    #[prost(bool, tag = "3")]
    pub compute_laplacian: bool,
    /// Use approximate TDA
    #[prost(bool, tag = "4")]
    pub approximate: bool,
    /// Maximum features to extract
    #[prost(int32, tag = "5")]
    pub max_features: i32,
    /// Normalize features
    #[prost(bool, tag = "6")]
    pub normalize: bool,
}
/// Topological data response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopologicalDataResponse {
    #[prost(message, optional, tag = "1")]
    pub persistence_diagram: ::core::option::Option<PersistenceDiagram>,
    #[prost(message, optional, tag = "2")]
    pub betti_numbers: ::core::option::Option<BettiNumbers>,
    #[prost(message, optional, tag = "3")]
    pub laplacian_spectrum: ::core::option::Option<LaplacianSpectrum>,
    #[prost(message, optional, tag = "4")]
    pub signature: ::core::option::Option<TopologicalSignature>,
    #[prost(message, optional, tag = "5")]
    pub metadata: ::core::option::Option<ComputationMetadata>,
}
/// Computation metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComputationMetadata {
    #[prost(double, tag = "1")]
    pub computation_time_ms: f64,
    #[prost(int64, tag = "2")]
    pub memory_used_bytes: i64,
    /// Algorithm used (e.g., "Ripser++", "PersistentLaplacian")
    #[prost(string, tag = "3")]
    pub algorithm: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub used_approximation: bool,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// Recursive topology request (for recursive connectome loops)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecursiveTopologyRequest {
    #[prost(string, tag = "1")]
    pub iteration_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub initial_data: ::core::option::Option<TopologicalData>,
    /// How many recursive iterations
    #[prost(int32, tag = "3")]
    pub recursion_depth: i32,
    #[prost(message, optional, tag = "4")]
    pub options: ::core::option::Option<TopologyOptions>,
}
/// Recursive topology response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecursiveTopologyResponse {
    #[prost(message, repeated, tag = "1")]
    pub iterations: ::prost::alloc::vec::Vec<TopologicalDataResponse>,
    /// Evolution of signatures
    #[prost(message, repeated, tag = "2")]
    pub evolution: ::prost::alloc::vec::Vec<TopologicalSignature>,
    #[prost(double, tag = "3")]
    pub total_computation_time_ms: f64,
}
/// Generated client implementations.
pub mod topological_analysis_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Topological Analysis Service
    #[derive(Debug, Clone)]
    pub struct TopologicalAnalysisServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TopologicalAnalysisServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TopologicalAnalysisServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TopologicalAnalysisServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TopologicalAnalysisServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Compute topological features
        pub async fn compute_topology(
            &mut self,
            request: impl tonic::IntoRequest<super::TopologicalDataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TopologicalDataResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.TopologicalAnalysisService/ComputeTopology",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "niodoo.rce.TopologicalAnalysisService",
                        "ComputeTopology",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Recursive topology computation
        pub async fn compute_recursive_topology(
            &mut self,
            request: impl tonic::IntoRequest<super::RecursiveTopologyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RecursiveTopologyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.TopologicalAnalysisService/ComputeRecursiveTopology",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "niodoo.rce.TopologicalAnalysisService",
                        "ComputeRecursiveTopology",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream topological computations
        pub async fn stream_topology(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::TopologicalDataRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TopologicalDataResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.TopologicalAnalysisService/StreamTopology",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "niodoo.rce.TopologicalAnalysisService",
                        "StreamTopology",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Convert topological signature to ONNX-compatible format
        pub async fn signature_to_tensor(
            &mut self,
            request: impl tonic::IntoRequest<super::TopologicalSignature>,
        ) -> std::result::Result<tonic::Response<super::Tensor>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/niodoo.rce.TopologicalAnalysisService/SignatureToTensor",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "niodoo.rce.TopologicalAnalysisService",
                        "SignatureToTensor",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod topological_analysis_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TopologicalAnalysisServiceServer.
    #[async_trait]
    pub trait TopologicalAnalysisService: std::marker::Send + std::marker::Sync + 'static {
        /// Compute topological features
        async fn compute_topology(
            &self,
            request: tonic::Request<super::TopologicalDataRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TopologicalDataResponse>,
            tonic::Status,
        >;
        /// Recursive topology computation
        async fn compute_recursive_topology(
            &self,
            request: tonic::Request<super::RecursiveTopologyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RecursiveTopologyResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamTopology method.
        type StreamTopologyStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TopologicalDataResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream topological computations
        async fn stream_topology(
            &self,
            request: tonic::Request<tonic::Streaming<super::TopologicalDataRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamTopologyStream>,
            tonic::Status,
        >;
        /// Convert topological signature to ONNX-compatible format
        async fn signature_to_tensor(
            &self,
            request: tonic::Request<super::TopologicalSignature>,
        ) -> std::result::Result<tonic::Response<super::Tensor>, tonic::Status>;
    }
    /// Topological Analysis Service
    #[derive(Debug)]
    pub struct TopologicalAnalysisServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TopologicalAnalysisServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for TopologicalAnalysisServiceServer<T>
    where
        T: TopologicalAnalysisService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/niodoo.rce.TopologicalAnalysisService/ComputeTopology" => {
                    #[allow(non_camel_case_types)]
                    struct ComputeTopologySvc<T: TopologicalAnalysisService>(pub Arc<T>);
                    impl<
                        T: TopologicalAnalysisService,
                    > tonic::server::UnaryService<super::TopologicalDataRequest>
                    for ComputeTopologySvc<T> {
                        type Response = super::TopologicalDataResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TopologicalDataRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TopologicalAnalysisService>::compute_topology(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ComputeTopologySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.TopologicalAnalysisService/ComputeRecursiveTopology" => {
                    #[allow(non_camel_case_types)]
                    struct ComputeRecursiveTopologySvc<T: TopologicalAnalysisService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: TopologicalAnalysisService,
                    > tonic::server::UnaryService<super::RecursiveTopologyRequest>
                    for ComputeRecursiveTopologySvc<T> {
                        type Response = super::RecursiveTopologyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RecursiveTopologyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TopologicalAnalysisService>::compute_recursive_topology(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ComputeRecursiveTopologySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.TopologicalAnalysisService/StreamTopology" => {
                    #[allow(non_camel_case_types)]
                    struct StreamTopologySvc<T: TopologicalAnalysisService>(pub Arc<T>);
                    impl<
                        T: TopologicalAnalysisService,
                    > tonic::server::StreamingService<super::TopologicalDataRequest>
                    for StreamTopologySvc<T> {
                        type Response = super::TopologicalDataResponse;
                        type ResponseStream = T::StreamTopologyStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::TopologicalDataRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TopologicalAnalysisService>::stream_topology(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamTopologySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/niodoo.rce.TopologicalAnalysisService/SignatureToTensor" => {
                    #[allow(non_camel_case_types)]
                    struct SignatureToTensorSvc<T: TopologicalAnalysisService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: TopologicalAnalysisService,
                    > tonic::server::UnaryService<super::TopologicalSignature>
                    for SignatureToTensorSvc<T> {
                        type Response = super::Tensor;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TopologicalSignature>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TopologicalAnalysisService>::signature_to_tensor(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SignatureToTensorSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TopologicalAnalysisServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "niodoo.rce.TopologicalAnalysisService";
    impl<T> tonic::server::NamedService for TopologicalAnalysisServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
