name: tcs-ml CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTONIG_SYSTEM_LIBONIG: "1"
  QWEN_MODEL_PATH: ${{ github.workspace }}/models/qwen2.5-coder-0.5b-instruct-onnx/onnx/model_quantized.onnx

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libonig-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo builds
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Qwen ONNX model
        id: cache-model
        uses: actions/cache@v4
        with:
          path: models/qwen2.5-coder-0.5b-instruct-onnx
          key: qwen-0.5b-onnx-v1

      - name: Download Qwen2.5-Coder-0.5B-Instruct ONNX model
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: |
          mkdir -p models/qwen2.5-coder-0.5b-instruct-onnx/onnx
          cd models/qwen2.5-coder-0.5b-instruct-onnx
          # Download model and tokenizer from HuggingFace
          wget -q https://huggingface.co/onnx-community/Qwen2.5-Coder-0.5B-Instruct/resolve/main/onnx/model_quantized.onnx -O onnx/model_quantized.onnx
          wget -q https://huggingface.co/onnx-community/Qwen2.5-Coder-0.5B-Instruct/resolve/main/tokenizer.json -O tokenizer.json

      - name: Configure ONNX Runtime path
        run: echo "LD_LIBRARY_PATH=${{ github.workspace }}/third_party/onnxruntime-linux-x64-1.18.1/lib:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

      - name: Cargo check (onnx feature)
        run: cargo check -p tcs-ml --lib --features onnx

      - name: Run stateful embedder smoke test
        run: cargo run -p tcs-ml --bin test_qwen_stateful --features onnx-with-tokenizers
